//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patronus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteArtiste
    {
        public string IdUser { get; set; }
        public string IdArtiste { get; set; }
        public double Note { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Artiste Artiste { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
